/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginAdminRouteImport } from './routes/login/admin'
import { Route as LoginCustomerRouteImport } from './routes/login/customer'
import { Route as LoginWorkerRouteImport } from './routes/login/worker'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCustomerRoute = LoginCustomerRouteImport.update({
  id: '/login/customer',
  path: '/login/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginWorkerRoute = LoginWorkerRouteImport.update({
  id: '/login/worker',
  path: '/login/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/customer': typeof LoginCustomerRoute
  '/login/worker': typeof LoginWorkerRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/customer': typeof LoginCustomerRoute
  '/login/worker': typeof LoginWorkerRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/customer': typeof LoginCustomerRoute
  '/login/worker': typeof LoginWorkerRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login/admin'
    | '/login/customer'
    | '/login/worker'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login/admin'
    | '/login/customer'
    | '/login/worker'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login/admin'
    | '/login/customer'
    | '/login/worker'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginCustomerRoute: typeof LoginCustomerRoute
  LoginWorkerRoute: typeof LoginWorkerRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/customer': {
      id: '/login/customer'
      path: '/login/customer'
      fullPath: '/login/customer'
      preLoaderRoute: typeof LoginCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/worker': {
      id: '/login/worker'
      path: '/login/worker'
      fullPath: '/login/worker'
      preLoaderRoute: typeof LoginWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginCustomerRoute: LoginCustomerRoute,
  LoginWorkerRoute: LoginWorkerRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
